### ISSUE TITLE
Event Likes

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#22] opened 2024-10-03 07:33 UTC
Add Event Likes Ui On Card and make it working with Supabase backend add this whole stuff on card in explore-event page and update the like once by user and on click remove and add show this also in explore-events/id

**Comment by abhishekpaturkar** [comment] 2024-10-04 16:53
Can you assign it to me under gssoc-ext and hacktoberfest.

**Comment by TejasNasre** [comment] 2024-10-04 16:58
Checkout for setup LEARN.md And After Completing Make PR to dev

**Comment by TejasNasre** [comment] 2024-10-05 18:58
@abhishekpaturkar any updates ?

**Comment by abhishekpaturkar** [comment] 2024-10-06 05:25
@TejasNasre Difficulties in project setup, trying to solve the issue as soon as possible.

**Comment by TejasNasre** [comment] 2024-10-06 09:19
refer LEARN.md if you have any problem you can pin me

**Comment by aasiflm10** [comment] 2024-10-07 15:45
@TejasNasre  can i also work on this issue?

**Comment by aasiflm10** [comment] 2024-10-07 17:22
One question : 
Are you using any ORM like prisma for database schema.  If not then which file contains the database schema file. 
I can do this by tomorrow.

**Comment by TejasNasre** [comment] 2024-10-08 15:56
refer LEARN.md

**Comment by aasiflm10** [comment] 2024-10-09 03:42
right now working on some other issue

**Comment by Hh440** [comment] 2024-10-09 13:37
@TejasNasre I would like to work on this issue

**Comment by TejasNasre** [comment] 2024-10-10 14:43
make PR by tomorrow if possible make sure the likes will work functionally don't add just ui and by one account only the single person should give like how the YouTube like works add same and the icon should heart

**Comment by meghanakn473** [comment] 2024-10-10 14:45
@TejasNasre i would like to work on this, can u assign me?

**Comment by TejasNasre** [comment] 2024-10-10 14:48
you are 5 min late just assign to other , solve other issues or make one

**Comment by TejasNasre** [comment] 2024-10-11 12:38
don't know why google it or delete all stuff and git clone it repeat

**Comment by Hh440** [comment] 2024-10-11 13:25
as mentioned in LEARN.md to create policies in authentication section under configuration but they are not being created tried many times.

**Comment by TejasNasre** [comment] 2024-10-11 14:28
refer videos its super easy

**Comment by TejasNasre** [comment] 2024-10-11 14:33
Uploading 2024-10-11 20-00-12.mp4…

**Comment by Hh440** [comment] 2024-10-11 16:17
when try create the polices nothing is being created

https://github.com/user-attachments/assets/882f7dfa-cedb-4762-ad7d-226a11c4e6ac

**Comment by TejasNasre** [comment] 2024-10-11 16:44
I will post video in some minutes

**Comment by TejasNasre** [comment] 2024-10-12 05:39
@Hh440 any updates ?

**Comment by Hh440** [comment] 2024-10-12 11:35
it still not functioning

**Comment by shreyamaheshwari1** [comment] 2024-10-13 06:16
@TejasNasre can i try working on it as well if the issue is still open ?

**Comment by TejasNasre** [comment] 2024-10-13 06:21
@shreyamaheshwari1 yeah but make PR as soon as possible

**Comment by shreyamaheshwari1** [comment] 2024-10-13 06:43
Sure I will try do it asap.

**Comment by shreyamaheshwari1** [comment] 2024-10-13 12:27
Hii @TejasNasre not sure how can I particpate in an event, I definitely can organise one and in the explore events when i visit i see those events that i have organised . Now if someone wants to like an event he will like the event he participated in for sure So i can create a supabase table for the same and integrate the backend . But how can i participate in an event? Could you explain a bit so that i can complete it early

**Comment by TejasNasre** [comment] 2024-10-13 14:45
https://github.com/user-attachments/assets/b1393544-492b-41bb-9ca9-20f648db4529

**Comment by TejasNasre** [comment] 2024-10-13 14:46
i you don't understand meet me on discord at 9 gssoc

**Comment by shreyamaheshwari1** [comment] 2024-10-13 15:03
> i you don't understand meet me on discord at 9 gssoc

OK. Thank you.

**Comment by TejasNasre** [comment] 2024-10-13 15:33
Join discord general gssoc

**Comment by shreyamaheshwari1** [comment] 2024-10-13 16:55
https://github.com/user-attachments/assets/39d104af-7fa9-4432-b904-19a62204710c

Hii @TejasNasre kindly have a look. Here in the explore events page i am only able to see the events organised by me and not others which i think there is some issue related to the permissions as I am not getting reading permissions to view other organisers events. Rest all functionality is working fine. But I have already added all the policies giving permissions to anon as well as authenticated users. If you could pinpoint the error it would be great.

**Comment by shreyamaheshwari1** [comment] 2024-10-14 05:42
https://github.com/user-attachments/assets/660dec52-8606-4020-9f30-a7e8ec03e744

@TejasNasre kindly review this . When i logged in again then my liked events are as it is and when i like someother events and dislike some othere the same count is reflected in the event_details table as well as the new entry of the liked events are being added in the check_event_likes table and if disliked they are removed from this table.

If this is fine then i can raise a pr. If not I can modify things .

**Comment by shreyamaheshwari1** [comment] 2024-10-14 14:10
@TejasNasre could you also review this is this is fine I can raise a pr?

**Comment by TejasNasre** [comment] 2024-10-14 14:35
there are some changes show the like number below the like add some padding like fix ui thing also and the  user id should be the email not actual user_id

**Comment by TejasNasre** [comment] 2024-10-14 14:37
update this things and update the LEARN.md and make PR to dev i will test and merge with main

**Comment by shreyamaheshwari1** [comment] 2024-10-14 14:39
Ok sure.

**Comment by shreyamaheshwari1** [comment] 2024-10-14 19:38
@TejasNasre I made the appropriate changes and raised the pr. Kindly review and approve.

**Closed** 2024-10-15 07:47 UTC
Labels: gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest
