### ISSUE TITLE
Integrate backend for sort by likes

### ISSUE THREAD

**Issue by shreyamaheshwari1** [TejasNasre/nexmeet#99] opened 2024-10-14 06:17 UTC
After the event likes backend is implemented , the sort by likes needs to be integrated with backend as well . Such that if we choose highest then events with the highest likes appear. I would like to work on it once the event likes feature is implemented.

**Comment by TejasNasre** [comment] 2024-10-14 13:49
make PR and as soon as possible and in initial rendering the events should be displayed by date which event is organized closest it should be displayed and have not any other constraints initially

**Comment by prisha-sh** [comment] 2024-10-14 17:51
hey kindly assign me this , I'll deliver asap !

**Comment by TejasNasre** [comment] 2024-10-14 18:00
@prisha-sh already assigned bro don't spam

**Comment by TejasNasre** [comment] 2024-10-15 07:49
@shreyamaheshwari1 i think the issue is solved

**Comment by TejasNasre** [comment] 2024-10-15 09:04
add one thing initial event rendering sort by recent event added and check the like thing if its not working properly then make changes there

**Comment by shreyamaheshwari1** [comment] 2024-10-15 13:32
Okay can it be assigned an appropriate level as well?

**Comment by TejasNasre** [comment] 2024-10-18 17:11
any updates ?

**Comment by shreyamaheshwari1** [comment] 2024-10-18 17:17
Hii @TejasNasre busy with some exams actually that's why it's getting delayed.

**Comment by TejasNasre** [comment] 2024-10-18 17:21
no worries

**Comment by TejasNasre** [comment] 2024-10-21 14:56
any updates @shreyamaheshwari1 if you are free please update if not i will assign to other

**Closed** 2024-10-21 17:57 UTC
Labels: enhancement, help wanted, good first issue, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest
